---
kind: Template
apiVersion: v1
metadata:
  name: icescrum
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    labels:
      app: icescrum
    name: icescrum
  spec:
    replicas: 1
    selector:
      app: icescrum
      deploymentconfig: icescrum
    template:
      metadata:
        labels:
          app: icescrum
          deploymentconfig: icescrum
      spec:
        containers:
        - image: zhrum/icescrum
          name: icescrum
          volumeMounts:
          - name: is-vol-1
            mountPath: "/root"
        volumes:
        - name: is-vol-1
          persistentVolumeClaim:
            claimName: is-data
        
- kind: ImageStream
  apiVersion: v1
  metadata:
    labels:
      app: icescrum
    name: icescrum
- kind: Route
  apiVersion: v1
  metadata:
    name: icescrumroute
  spec:
    to:
      kind: Service
      name: icescrumservice
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: icescrum
    name: icescrumservice
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: icescrum
      deploymentconfig: icescrum
    type: ClusterIP
- kind: ImageStream
  apiVersion: v1
  metadata:
    labels:
      app: postgresql
    name: postgresql
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: is-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  status:
    accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
    capacity:
      storage: 100Gi
    phase: Bound
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 2
    labels:
      app: postgresql-persistent
      template: postgresql-persistent-template
    name: postgresql
  spec:
    replicas: 1
    selector:
      name: postgresql
    template:
      metadata:
        labels:
          name: postgresql
      spec:
        containers:
        - env:
          - name: POSTGRESQL_USER
            value: admin
          - name: POSTGRESQL_PASSWORD
            value: admin
          - name: POSTGRESQL_DATABASE
            value: icescrum
          image: centos/postgresql-95-centos7@sha256:2a107a9739647d9768c29841e00229a9009f47dd415c06bc53e19d720fc6c886
          name: postgresql
          ports:
          - containerPort: 5432
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c
                'SELECT 1'
          resources:
            limits:
              memory: 512Mi
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: postgresql-data
        volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
    labels:
      app: postgresql-persistent
      template: postgresql-persistent-template
    name: postgresql
  spec:
    ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      name: postgresql
    type: ClusterIP
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: postgresql
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  status:
    accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
    capacity:
      storage: 100Gi            
